name: ArlenesHennaArt
favicon: null
layout_spectrum: 0.7023941068910062
typography_spectrum: 0.3313151521142572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7862369378563017
  lightness: 0.7164610687177628
  saturation: 0.7362957035657018
  rhythmicContrast: 0.36785730673000216
purpose: []
